import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="nav">
        <h2>
          {" "}
          <Link href="./users/users-nossr">Users No SSR</Link>
        </h2>
        <h2>
          <Link href="./users/users-ssr">Users SSR</Link>
        </h2>
      </div>
      <p>Hello Next JS</p>
    </div>
  );
}
